os: linux
language: python
python:
  - "3.8.5"
dist: bionic
group: beta

services:
  - docker

before_install:
  - test -z "$TRAVIS_TAG" && export VERSION=github-travis-$TRAVIS_BUILD_NUMBER-$(date +%Y%m%d-%H%M%S) || export VERSION=$TRAVIS_TAG
  - echo "Build Version=$VERSION"
install:
  - make setup

script:
  - make travis-test

deploy:
  provider: script
  script: make travis-deploy
  cleanup: false
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = main || ! -z $TRAVIS_TAG

cache:
  directories:
    - $HOME/.cache/trivy
    - $HOME/.cache/pre-commit
